### ISSUE TITLE
代码有误，err哪里来的

### ISSUE THREAD

**Issue by jonnywang** [Unknwon/go-rock-libraries-showcases#10]
// 对已有的键进行值重写操作，返回值为 bool 类型，表示是否为插入操作
	isInsert := cfg.SetValue(goconfig.DEFAULT_SECTION, "key_default", "这是新的值")
	if err != nil {   //err哪里来的
		log.Fatalf("无法设置键值（%s）：%s", "key_default", err)
	}
	log.Printf("设置键值 %s 为插入操作：%v", "key_default", isInsert)

**Comment by Unknwon** [comment]
多谢指正！已修复。
